### ISSUE TITLE
How does it handle re-renders?

### ISSUE THREAD

**Issue by filipemerker** [Aslemammad/contextism#1]
I love the design, congrats on the lib!

However, last time I did try and use context as a state management tool, I've run into a re-render issue where any update on the store would result into re-renders on all components that read from it.

Does this lib try to prevent this in any way, or is it just an abstraction for a context state management setup?

**Comment by Aslemammad** [comment]
Hey @filipemerker. How are you doing?☕ I think this Context property( re-rendering) is not the main problem, I think we should use context itself in a better way. read [this](https://kentcdodds.com/blog/how-to-use-react-context-effectively), this article shows you how to use context better in a more efficient way, This is why I created Contextism, It's based on that article. it uses the better way, So don't worry about the power of React and Context + Contextism. In the future, we will have better state management experience with [recoil](https://recoiljs.org/). So be happy with Contextism. ♥️

**Comment by Aslemammad** [comment]
I think if you done with this issue, close it, please. ♥️

**Comment by filipemerker** [comment]
@Aslemammad Using recoil is a great idea!
